enhance resolve-site-name script
Adds the ability to pass in --unbound and --dnssec parameters
to influence the resolver setup prior to resolving the site name.

In order to facilitate this, the --script-args handling in kumod
has been given a little facelift: that option has been deprecated
in favor of just collecting an argument list via:

`kumod --script -- arg1 arg2`

which is much more natural and easier to wrangle in the context
of the shell script wrapper that we use for this today.

The old way is preserved for compatibility in case someone is
using this already.

I've also added a requires flag on both the legacy and the
preferred script arguments list to ensure that --script is
used together with it.

diff --git a/assets/resolve-site-name b/assets/resolve-site-name
--- a/assets/resolve-site-name
+++ b/assets/resolve-site-name
@@ -1,16 +1,20 @@
 #!/bin/sh
 CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-${PWD}/target}
 
-for candidate in /opt/kumomta/sbin/kumod "${CARGO_TARGET_DIR}/release/kumod" "${CARGO_TARGET_DIR}/debug/kumod" ; do
-  if test -x "${candidate}" ; then
-    KUMOD="${candidate}"
-    break;
-  fi
-done
+KUMOD=${KUMOD:-kumod}
 
-if ! test -x "${KUMOD}" ; then
-  echo "Couldn't find kumod"
-  exit 1
+if ! test -x ${KUMOD} ; then
+  for candidate in /opt/kumomta/sbin/kumod "${CARGO_TARGET_DIR}/release/kumod" "${CARGO_TARGET_DIR}/debug/kumod" ; do
+    if test -x "${candidate}" ; then
+      KUMOD="${candidate}"
+      break;
+    fi
+  done
+
+  if ! test -x "${KUMOD}" ; then
+    echo "Couldn't find kumod"
+    exit 1
+  fi
 fi
 
 script=$(mktemp)
@@ -18,11 +22,57 @@ trap "rm -f -- '$script'" EXIT
 cat >${script} <<-EOT
 local kumo = require 'kumo'
 
-kumo.on('main', function(domain)
+kumo.on('main', function(...)
+  local args = table.pack(...)
+  local use_unbound = false
+  local use_dnssec = false
+  local domain = nil
+
+  for _, arg in ipairs(args) do
+    if arg == "--unbound" then
+      use_unbound = true
+    elseif arg == "--dnssec" then
+      use_dnssec = true
+    elseif arg == "--help" or arg == "-h" then
+      print [[
+Resolves the effective MX record for a domain and displays
+the kumomta site-name that is produced from its MX host list.
+
+resolve-site-name [OPTIONS] DOMAIN_NAME
+
+OPTIONS:
+
+  --unbound
+    Use the unbound resolver instead of the default hickory resolver
+
+  --dnssec
+    When using unbound, enable DNSSEC validation
+
+]]
+      return
+    elseif arg:sub(1, 1) == "-" then
+      error("unknown option", arg)
+    else
+      domain = arg
+    end
+  end
+
+  if not domain then
+    error("missing domain name")
+  end
+
+  if use_unbound then
+    kumo.dns.configure_unbound_resolver {
+      options = {
+        validate = use_dnssec,
+      },
+    }
+  end
+
   local mx = kumo.dns.lookup_mx(domain)
   print(mx.site_name)
 end)
 EOT
 
-${KUMOD} --policy $script --script --script-args "$1"
+${KUMOD} --policy $script --script -- "$@"
 
